export * from "./api/client.gen.ts"
export * from "./common/errors/index.ts"
//export { gql } from "npm:graphql-tag@2.12.6"
export { GraphQLClient } from "npm:graphql-request@6.1.0"
export type { CallbackFct } from "./connect.ts"
export { connect, connection, close } from "./connect.ts"
export type { ConnectOpts } from "./connectOpts.ts"
export * from "./introspector/decorators/decorators.ts"
export { entrypoint } from "./entrypoint/entrypoint.ts"
